CREATE TABLE IF NOT EXISTS agentpilot_admin_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    actor_user_id BIGINT NOT NULL,
    action VARCHAR(128) NOT NULL,
    target_type VARCHAR(128) NOT NULL,
    target_id VARCHAR(128) NOT NULL,
    summary VARCHAR(1024) NOT NULL,
    trace_id VARCHAR(128),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_tenant_created
    ON agentpilot_admin_audit_log(tenant_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_audit_action
    ON agentpilot_admin_audit_log(action, created_at DESC);
