CREATE TABLE IF NOT EXISTS crm_sales_rep (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    mobile VARCHAR(32),
    team_name VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS crm_customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    industry VARCHAR(64),
    city VARCHAR(64),
    address VARCHAR(255),
    contact_name VARCHAR(64),
    contact_mobile VARCHAR(32),
    lifecycle_stage VARCHAR(32),
    value_level VARCHAR(32),
    risk_level VARCHAR(32),
    owner_sales_rep_id BIGINT NOT NULL,
    last_contact_at TIMESTAMP,
    next_follow_time TIMESTAMP,
    package_expire_at TIMESTAMP,
    tags VARCHAR(512),
    remark TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS crm_lead (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    sales_rep_id BIGINT NOT NULL,
    source VARCHAR(64),
    stage VARCHAR(32) NOT NULL,
    intent_level VARCHAR(32),
    estimated_amount NUMERIC(12,2),
    expected_close_date DATE,
    score NUMERIC(8,2),
    score_reason TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS crm_contact_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    sales_rep_id BIGINT NOT NULL,
    lead_id BIGINT,
    channel VARCHAR(32),
    content TEXT NOT NULL,
    summary TEXT,
    customer_intent VARCHAR(32),
    objections VARCHAR(512),
    next_action TEXT,
    contact_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS crm_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    lead_id BIGINT,
    sales_rep_id BIGINT NOT NULL,
    title VARCHAR(128) NOT NULL,
    content TEXT,
    due_time TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    source VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    idempotency_key VARCHAR(128),
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_crm_task_idempotency_key UNIQUE (idempotency_key)
);

CREATE TABLE IF NOT EXISTS crm_product_package (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    industry VARCHAR(64),
    price NUMERIC(12,2),
    duration_days INT,
    benefits TEXT,
    limitations TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_crm_customer_owner ON crm_customer(owner_sales_rep_id);
CREATE INDEX IF NOT EXISTS idx_crm_lead_sales_rep ON crm_lead(sales_rep_id);
CREATE INDEX IF NOT EXISTS idx_crm_lead_customer ON crm_lead(customer_id);
CREATE INDEX IF NOT EXISTS idx_crm_contact_customer ON crm_contact_log(customer_id);
CREATE INDEX IF NOT EXISTS idx_crm_task_sales_rep ON crm_task(sales_rep_id);

