CREATE TABLE IF NOT EXISTS agentpilot_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    sales_rep_id BIGINT,
    type VARCHAR(64) NOT NULL,
    title VARCHAR(160) NOT NULL,
    content VARCHAR(1024) NOT NULL,
    action_url VARCHAR(512),
    source_type VARCHAR(64),
    source_id VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'UNREAD',
    dedupe_key VARCHAR(256) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP,
    CONSTRAINT uk_agentpilot_notification_dedupe UNIQUE (tenant_id, recipient_user_id, dedupe_key)
);

CREATE INDEX IF NOT EXISTS idx_notification_recipient_status
    ON agentpilot_notification(tenant_id, recipient_user_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notification_source
    ON agentpilot_notification(tenant_id, source_type, source_id);
