CREATE TABLE IF NOT EXISTS agentpilot_webhook_replay_guard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    endpoint VARCHAR(128) NOT NULL,
    nonce VARCHAR(128) NOT NULL,
    signature_hash VARCHAR(128) NOT NULL,
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_webhook_replay_nonce UNIQUE (tenant_id, endpoint, nonce)
);

CREATE INDEX IF NOT EXISTS idx_webhook_replay_expires
    ON agentpilot_webhook_replay_guard(expires_at);
