CREATE TABLE IF NOT EXISTS agentpilot_tenant_config (
    tenant_id VARCHAR(64) NOT NULL,
    config_key VARCHAR(128) NOT NULL,
    config_value VARCHAR(1024),
    value_type VARCHAR(32) NOT NULL DEFAULT 'string',
    description VARCHAR(512),
    updated_by BIGINT,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, config_key)
);

CREATE INDEX IF NOT EXISTS idx_tenant_config_tenant
    ON agentpilot_tenant_config(tenant_id);

CREATE TABLE IF NOT EXISTS agentpilot_export_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    requester_user_id BIGINT NOT NULL,
    export_type VARCHAR(64) NOT NULL,
    reason VARCHAR(512) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    approver_user_id BIGINT,
    approval_comment VARCHAR(512),
    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decided_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_export_request_tenant_status
    ON agentpilot_export_request(tenant_id, status, requested_at);

INSERT INTO agentpilot_permission (id, code, name) VALUES
(12, 'export:request', 'Request business data exports'),
(13, 'export:approve', 'Approve or reject business data exports');

INSERT INTO agentpilot_role_permission (role_id, permission_id) VALUES
(2, 12),
(3, 12),
(3, 13);
