CREATE TABLE IF NOT EXISTS crm_knowledge_doc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    doc_type VARCHAR(64) NOT NULL,
    source VARCHAR(128),
    content_hash VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS crm_knowledge_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id BIGINT NOT NULL,
    chunk_index INT NOT NULL,
    title VARCHAR(255),
    content TEXT NOT NULL,
    token_count INT,
    keywords TEXT,
    embedding TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS crm_retrieval_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT,
    query TEXT NOT NULL,
    rewritten_query TEXT,
    retriever_type VARCHAR(64),
    top_k INT,
    result_json TEXT,
    latency_ms BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_knowledge_chunk_doc_id ON crm_knowledge_chunk(doc_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_doc_type ON crm_knowledge_doc(doc_type);
CREATE INDEX IF NOT EXISTS idx_retrieval_log_created_at ON crm_retrieval_log(created_at);

